language: csharp
solution: Kentor.AuthServices.sln
dist: trusty # see: https://github.com/travis-ci/travis-ci/issues/6805
#sudo: required
matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - mono: latest